# Usuário e senha do banco
spring.flyway.user=root
spring.flyway.password=root

# URL do banco MySQL (ajuste se necessário)
spring.flyway.url=jdbc:mysql://db:3306/gerenciador_compromissos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#flyway.url=jdbc:mysql://db:3306/gerenciador_compromissos

# Esquema padrão (MySQL normalmente usa 'public' só em PostgreSQL, pode remover)
# spring.flyway.schemas=public

# Localização das migrations
spring.flyway.locations=classpath:db/migration

# Ativar Flyway
spring.flyway.enabled=true

# Baseline para banco que já possui dados
spring.flyway.baseline-on-migrate=true


